language: java
jdk: openjdk13
before_install:
  - sudo apt-get update
  - sudo apt-get install libc6
dist: focal
install: true
cache:
  directories:
    - $HOME/.m2
script:
  - mvn test -B
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: keepid:dSU1H1ttrbqa2CuH1d2CVui3
env:
  global:
    - CODECOV_TOKEN="6ede0adf-a688-47e1-9221-0553d6d07654"
