language: java
jdk: oraclejdk13
before_install:
  - sudo apt-get update
  - sudo apt-get install libc6
dist: bionic
install: true
script:
  - mvn test -B
cache:
  directories:
    - $HOME/.m2
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: keepid:dSU1H1ttrbqa2CuH1d2CVui3
env:
  global:
    - CODECOV_TOKEN=4b9c6987-3c19-46a7-b4cc-0b8a1aabfd7b