language: java
jdk: oraclejdk13
before_install:
  - sudo apt-get update
  - sudo apt-get install libc6
dist: bionic
install: true
script:
  - mvn test -B
#  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
cache:
  directories:
    - $HOME/.m2